#!/usr/bin/env bash
set -euo pipefail

# cc — Claude Code devcontainer CLI
# Reusable entry point for running Claude in isolated Docker containers.
# https://github.com/anthropics/claude-code/.devcontainer

CC_TEMPLATE_DIR="${CC_TEMPLATE_DIR:-$(cd "$(dirname "$(readlink -f "$0" 2>/dev/null || echo "$0")")" && pwd)}"
CC_CONF=".devcontainer/cc.conf"

# --- helpers ---

die() { echo "error: $*" >&2; exit 1; }

load_conf() {
    [[ -f "$CC_CONF" ]] || die "no $CC_CONF found — run 'cc init' first"
    # shellcheck disable=SC1090
    source "$CC_CONF"
}

repo_name() { basename "$(pwd)"; }

container_running() {
    docker ps --format '{{.Names}}' | grep -qx "${CONTAINER_NAME:-}" 2>/dev/null
}

container_exists() {
    docker ps -a --format '{{.Names}}' | grep -qx "${CONTAINER_NAME:-}" 2>/dev/null
}

port_flags() {
    local flags=""
    for mapping in $PORTS; do
        flags="$flags -p $mapping"
    done
    echo "$flags"
}

# --- commands ---

cmd_init() {
    local stack="node"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --stack) stack="$2"; shift 2 ;;
            *) die "unknown option: $1" ;;
        esac
    done

    mkdir -p .devcontainer

    # Combine base + stack Dockerfile(s)
    echo "# Generated by cc init --stack $stack" > .devcontainer/Dockerfile
    echo "# Do not edit — regenerate with: cc init --stack $stack" >> .devcontainer/Dockerfile
    echo "" >> .devcontainer/Dockerfile
    cat "$CC_TEMPLATE_DIR/.devcontainer/Dockerfile.base" >> .devcontainer/Dockerfile

    local extra_domains=""
    IFS=',' read -ra stacks <<< "$stack"
    for s in "${stacks[@]}"; do
        local stack_file="$CC_TEMPLATE_DIR/stacks/${s}.Dockerfile"
        [[ -f "$stack_file" ]] || die "unknown stack: $s (no $stack_file)"
        echo "" >> .devcontainer/Dockerfile
        cat "$stack_file" >> .devcontainer/Dockerfile

        # Extract extra firewall domains from stack comment
        local domains
        domains=$(grep '^# Extra firewall domains:' "$stack_file" | sed 's/^# Extra firewall domains: //' || true)
        if [[ -n "$domains" ]]; then
            extra_domains="${extra_domains:+$extra_domains }$domains"
        fi
    done

    # Copy firewall script
    cp "$CC_TEMPLATE_DIR/.devcontainer/init-firewall.sh" .devcontainer/init-firewall.sh
    chmod +x .devcontainer/init-firewall.sh

    # Generate cc.conf
    local name ports
    name="cc-$(repo_name)"
    ports="3000:3000 5173:5173"
    cat > "$CC_CONF" <<EOF
# .devcontainer/cc.conf — per-repo Claude devcontainer config
# Generated by: cc init --stack $stack
STACK=$stack
CONTAINER_NAME=$name
PORTS="$ports"
EXTRA_FIREWALL_DOMAINS="$extra_domains"
EXTRA_APT=""
CLAUDE_FLAGS="--dangerously-skip-permissions"
EOF

    # Generate firewall-extra-domains.txt
    if [[ -n "$extra_domains" ]]; then
        echo "# Extra firewall domains for stack: $stack" > .devcontainer/firewall-extra-domains.txt
        for d in $extra_domains; do
            echo "$d" >> .devcontainer/firewall-extra-domains.txt
        done
    fi

    # Generate devcontainer.json from template — extract port numbers from PORTS
    local ports_csv
    ports_csv=$(echo "$ports" | tr ' ' '\n' | cut -d: -f1 | paste -sd, - | sed 's/,/, /g')
    sed "s/__PORTS__/$ports_csv/" \
        "$CC_TEMPLATE_DIR/.devcontainer/devcontainer.json.template" \
        > .devcontainer/devcontainer.json

    echo "Initialized .devcontainer/ with stack: $stack"
    echo "  Container name: $name"
    echo "  Edit $CC_CONF to customize ports, domains, etc."
    echo ""
    echo "Next: cc build && cc start"
}

cmd_build() {
    load_conf
    local image_name="${CONTAINER_NAME}"
    echo "Building image $image_name..."
    docker build -t "$image_name" .devcontainer/
}

cmd_start() {
    load_conf
    if container_running; then
        echo "Container $CONTAINER_NAME already running. Use 'cc shell' to open a shell."
        return
    fi

    if container_exists; then
        echo "Starting existing container $CONTAINER_NAME..."
        docker start "$CONTAINER_NAME"
    else
        echo "Creating container $CONTAINER_NAME..."
        # shellcheck disable=SC2046,SC2086
        docker run -d \
            --name "$CONTAINER_NAME" \
            --cap-add=NET_ADMIN --cap-add=NET_RAW \
            -v "$(pwd):/workspace:delegated" \
            -v "cc-bashhistory-${CONTAINER_NAME}:/commandhistory" \
            -v "cc-claude-config-${CONTAINER_NAME}:/home/node/.claude" \
            $(port_flags) \
            -e "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}" \
            -e "GH_TOKEN=${GH_TOKEN:-}" \
            -e "CLAUDE_CONFIG_DIR=/home/node/.claude" \
            "$CONTAINER_NAME" \
            bash -c "sudo /usr/local/bin/init-firewall.sh && sleep infinity"
    fi

    echo "Waiting for container..."
    sleep 2

    if ! container_running; then
        echo "Container failed to start. Logs:"
        docker logs "$CONTAINER_NAME" 2>&1 | tail -20
        die "container $CONTAINER_NAME is not running"
    fi

    echo "Container ready. Open a shell with: cc shell"
}

cmd_attach() {
    load_conf
    container_running || die "container $CONTAINER_NAME is not running — run 'cc start'"
    docker exec -it "$CONTAINER_NAME" bash
}

cmd_stop() {
    load_conf
    if container_running; then
        echo "Stopping $CONTAINER_NAME..."
        docker stop "$CONTAINER_NAME" >/dev/null
    fi
    if container_exists; then
        echo "Removing $CONTAINER_NAME..."
        docker rm "$CONTAINER_NAME" >/dev/null
    fi
    echo "Done."
}

cmd_shell() {
    load_conf
    container_running || die "container $CONTAINER_NAME is not running — run 'cc start'"
    local branch="${1:-}"
    if [[ -n "$branch" ]]; then
        docker exec -it -w "/workspace/.worktrees/$branch" "$CONTAINER_NAME" bash
    else
        docker exec -it "$CONTAINER_NAME" bash
    fi
}

cmd_claude() {
    load_conf
    container_running || die "container $CONTAINER_NAME is not running — run 'cc start'"
    local branch="${1:-}"
    local workdir="/workspace"
    if [[ -n "$branch" ]]; then
        workdir="/workspace/.worktrees/$branch"
    fi
    # shellcheck disable=SC2086
    docker exec -it -w "$workdir" "$CONTAINER_NAME" claude ${CLAUDE_FLAGS:-}
}

cmd_status() {
    echo "Running cc containers:"
    docker ps --filter "name=cc-" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || echo "  (none)"
}

cmd_rebuild() {
    load_conf
    cmd_stop
    cmd_build
    cmd_start
}

cmd_urls() {
    load_conf
    echo "Forwarded ports for $CONTAINER_NAME:"
    for mapping in $PORTS; do
        local host_port="${mapping%%:*}"
        echo "  http://localhost:$host_port"
    done
}

cmd_worktree() {
    load_conf
    local action="${1:-list}"
    shift || true

    case "$action" in
        add)
            local branch="${1:-}"
            [[ -n "$branch" ]] || die "usage: cc worktree add <branch-name>"
            local wt_dir="/workspace/.worktrees/$branch"
            container_running || die "container $CONTAINER_NAME is not running — run 'cc start'"
            docker exec -it "$CONTAINER_NAME" git worktree add "$wt_dir" -b "$branch" 2>/dev/null \
                || docker exec -it "$CONTAINER_NAME" git worktree add "$wt_dir" "$branch"
            echo "Worktree ready: $wt_dir"
            echo "Open a shell:  cc shell $branch"
            ;;
        list)
            container_running || die "container $CONTAINER_NAME is not running — run 'cc start'"
            docker exec -it "$CONTAINER_NAME" git worktree list
            ;;
        remove)
            local branch="${1:-}"
            [[ -n "$branch" ]] || die "usage: cc worktree remove <branch-name>"
            container_running || die "container $CONTAINER_NAME is not running — run 'cc start'"
            docker exec -it "$CONTAINER_NAME" git worktree remove "/workspace/.worktrees/$branch"
            echo "Removed worktree: $branch"
            ;;
        *)
            die "usage: cc worktree [add|list|remove] [branch-name]"
            ;;
    esac
}

cmd_help() {
    cat <<'EOF'
cc — Claude Code devcontainer CLI

  Run Claude with --dangerously-skip-permissions inside an isolated
  Docker container with iptables firewall, non-root user, and no
  host filesystem access. Based on Anthropic's official devcontainer.

Setup (once per repo):
  cc init --stack rust      Initialize .devcontainer/ from template
  cc build                  Build the Docker image

Daily workflow:
  cc start                  Start container in background
  cc shell                  Open shell in /workspace
  cc claude                 Launch Claude (bypass-permissions mode)
  cc urls                   Show forwarded port URLs
  cc stop                   Stop and remove container

Feature branches (worktrees):
  cc worktree add feature-x   Create worktree + branch
  cc shell feature-x          Shell into worktree
  cc claude feature-x         Claude in worktree
  cc worktree list             List worktrees
  cc worktree remove feature-x Clean up

Other:
  cc attach                 Open a shell (alias for shell)
  cc status                 List all running cc containers
  cc rebuild                Stop + build + start

Stacks: rust, node, python, go (combine with: --stack rust,python)

Environment variables:
  ANTHROPIC_API_KEY         Claude auth (passed into container)
  GH_TOKEN                  GitHub auth (passed into container)
  CC_TEMPLATE_DIR           Override template location

Typical session:
  cd ~/dev/my-project
  cc init --stack rust && cc build    # first time only
  cc start                            # start container
  cc worktree add feature-x           # new feature branch
  cc claude feature-x                 # Claude in worktree
  # ... work in host tmux windows ...
  cc worktree remove feature-x        # clean up
  cc stop                             # end of day
EOF
}

cmd_install() {
    local target="${HOME}/bin/cc"
    mkdir -p "$(dirname "$target")"
    ln -sf "$CC_TEMPLATE_DIR/cc" "$target"
    echo "Installed: $target -> $CC_TEMPLATE_DIR/cc"

    # Check PATH
    if ! echo "$PATH" | tr ':' '\n' | grep -qx "$HOME/bin"; then
        echo ""
        echo "Add to your shell profile (~/.zshrc or ~/.bashrc):"
        echo "  export PATH=\"\$HOME/bin:\$PATH\""
    fi
    echo ""
    echo "Done. Run 'cc help' from any repo."
}

# --- main ---

case "${1:-help}" in
    init)      shift; cmd_init "$@" ;;
    build)     cmd_build ;;
    start)     cmd_start ;;
    attach)    cmd_attach ;;
    stop)      cmd_stop ;;
    shell)     shift; cmd_shell "$@" ;;
    claude)    shift; cmd_claude "$@" ;;
    status)    cmd_status ;;
    rebuild)   cmd_rebuild ;;
    urls)      cmd_urls ;;
    worktree)  shift; cmd_worktree "$@" ;;
    install)   cmd_install ;;
    help|--help|-h) cmd_help ;;
    *)         die "unknown command: $1 — run 'cc help'" ;;
esac
